// Copyright 2026 Redpanda Data, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Lazy tool loading with remote MCP servers.
//
// The agent connects to public MCP servers and registers their tools deferred,
// keeping one entry point per server always loaded. That is the whole
// configuration: mcp.WithDeferredTools, mcp.WithAlwaysLoad and
// mcp.WithToolGroup on each client, and tool.NewGroup for the tools written in
// code. The agent lazy-loads by itself.
//
//	go run .                          # dry run: connect, show what the model would see
//	ANTHROPIC_API_KEY=... go run .    # interactive
//	ANTHROPIC_API_KEY=... go run . "how does the redpanda-data/console repo handle auth?"
//
// OPENAI_API_KEY works too. CONTEXT7_API_KEY adds a third server.
package main

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"github.com/redpanda-data/ai-sdk-go/agent"
	"github.com/redpanda-data/ai-sdk-go/agent/llmagent"
	"github.com/redpanda-data/ai-sdk-go/llm"
	"github.com/redpanda-data/ai-sdk-go/llm/fakellm"
	"github.com/redpanda-data/ai-sdk-go/providers/anthropic"
	"github.com/redpanda-data/ai-sdk-go/providers/openai"
	"github.com/redpanda-data/ai-sdk-go/runner"
	"github.com/redpanda-data/ai-sdk-go/store/session"
	"github.com/redpanda-data/ai-sdk-go/tool"
	"github.com/redpanda-data/ai-sdk-go/tool/builtin/todo"
	"github.com/redpanda-data/ai-sdk-go/tool/mcp"
)

const systemPrompt = "You are a research assistant for software engineers. Use the tools to answer " +
	"from primary sources and cite what you used."

func main() {
	ctx := context.Background()
	registry := tool.NewRegistry(tool.RegistryConfig{})

	startCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	// Each MCP server is a group. Everything but its entry point is deferred;
	// the group's description and instructions go into the system prompt.
	// Remove WithDeferredTools from a client to see the always-on request.
	deepwiki, err := mcp.NewClient("deepwiki", mcp.NewStreamableTransport("https://mcp.deepwiki.com/mcp"),
		mcp.WithRegistry(registry),
		mcp.WithDeferredTools(),
		mcp.WithAlwaysLoad("ask_question"),
		mcp.WithToolGroup(llm.ToolGroup{
			Description:  "Documentation of public GitHub repositories, generated by DeepWiki",
			Instructions: "Repositories are named owner/repo. Prefer ask_question; read the wiki structure only when the question needs a specific page.",
		}),
	)
	if err != nil {
		log.Fatal(err)
	}

	if err := deepwiki.Start(startCtx); err != nil {
		fmt.Printf("skipping deepwiki: %v\n", err)
	}

	mslearn, err := mcp.NewClient("mslearn", mcp.NewStreamableTransport("https://learn.microsoft.com/api/mcp"),
		mcp.WithRegistry(registry),
		mcp.WithDeferredTools(),
		mcp.WithAlwaysLoad("microsoft_docs_search"),
		mcp.WithToolGroup(llm.ToolGroup{
			Description:  "Microsoft Learn documentation and code samples",
			Instructions: "Search first; fetch a page only to quote or verify details the search result does not contain.",
		}),
	)
	if err != nil {
		log.Fatal(err)
	}

	if err := mslearn.Start(startCtx); err != nil {
		fmt.Printf("skipping mslearn: %v\n", err)
	}

	if key := os.Getenv("CONTEXT7_API_KEY"); key != "" {
		context7, err := mcp.NewClient("context7",
			mcp.NewStreamableTransport("https://mcp.context7.com/mcp",
				mcp.WithHTTPHeaders(map[string]string{"CONTEXT7_API_KEY": key})),
			mcp.WithRegistry(registry),
			mcp.WithDeferredTools(),
			mcp.WithAlwaysLoad("resolve-library-id"),
			mcp.WithToolGroup(llm.ToolGroup{
				Description:  "Version-specific documentation for open source libraries",
				Instructions: "Resolve the library ID before querying docs.",
			}),
		)
		if err != nil {
			log.Fatal(err)
		}

		if err := context7.Start(startCtx); err != nil {
			fmt.Printf("skipping context7: %v\n", err)
		}
	}

	if len(registry.List()) == 0 {
		log.Fatal("no MCP server reachable")
	}

	// Tools written in code are grouped the same way.
	planning := tool.NewGroup(llm.ToolGroup{
		Name:         "planning",
		Description:  "A todo list for multi-step work",
		Instructions: "Plan before you start a task that needs more than two tool calls.",
	})
	planning.Add(todo.NewAddTool()).AddDeferred(todo.NewUpdateStateTool())

	if err := planning.Register(registry); err != nil {
		log.Fatal(err)
	}

	printRegistry(registry)

	model, err := newModel()
	if err != nil {
		fmt.Printf("\n%v - showing what the model would see instead.\n", err)
		dryRun(ctx, registry)

		return
	}

	ag, err := llmagent.New("research", systemPrompt, model,
		llmagent.WithTools(registry),
		llmagent.WithInterceptors(&requestLogger{}),
	)
	if err != nil {
		log.Fatal(err)
	}

	store := session.NewInMemoryStore()

	r, err := runner.New(ag, store)
	if err != nil {
		log.Fatal(err)
	}

	const sessionID = "lazy-tools-demo"

	if len(os.Args) > 1 {
		turn(ctx, r, store, sessionID, strings.Join(os.Args[1:], " "))
		return
	}

	fmt.Println("\nTry: 'how does the redpanda-data/console repo handle authentication?',")
	fmt.Println("then 'is there a Microsoft Learn page on OAuth device code flow?'. Type 'quit' to exit.")

	scanner := bufio.NewScanner(os.Stdin)

	for {
		fmt.Print("\n> ")

		if !scanner.Scan() {
			return
		}

		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}

		if line == "quit" || line == "exit" {
			return
		}

		turn(ctx, r, store, sessionID, line)
	}
}

// printRegistry shows the registration policy the agent will act on.
func printRegistry(registry tool.Registry) {
	fmt.Println("registered tools:")

	for _, def := range registry.List() {
		state := "always loaded"
		if def.Deferred {
			state = "deferred"
		}

		fmt.Printf("  %-40s %-14s group=%s\n", def.Name, state, def.Group.Name)
	}
}

// dryRun sends one turn to a fake model and prints the request it received:
// the tools array and the generated system-prompt sections. No API key needed.
func dryRun(ctx context.Context, registry tool.Registry) {
	model := fakellm.NewFakeModel()
	model.When(fakellm.Any()).ThenRespondText("(dry run)")

	ag, err := llmagent.New("research", systemPrompt, model, llmagent.WithTools(registry))
	if err != nil {
		log.Fatal(err)
	}

	sess := &session.State{
		ID:       "dry-run",
		Messages: []llm.Message{llm.NewMessage(llm.RoleUser, llm.NewTextPart("hello"))},
	}

	for _, err := range ag.Run(ctx, agent.NewInvocationMetadata(sess, agent.Info{})) {
		if err != nil {
			log.Fatal(err)
		}
	}

	call, err := model.FirstCall()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("\ntools array sent to the model (%d):\n", len(call.Request.Tools))

	for _, def := range call.Request.Tools {
		fmt.Printf("  %s\n", def.Name)
	}

	fmt.Println("\nsystem prompt sent to the model:")
	fmt.Println(indent(call.Request.Messages[0].TextContent()))
}

// turn runs one user message and prints what the agent did with it.
func turn(ctx context.Context, r *runner.Runner, store session.Store, sessionID, text string) {
	for evt, err := range r.Run(ctx, "user", sessionID, llm.NewMessage(llm.RoleUser, llm.NewTextPart(text))) {
		if err != nil {
			fmt.Printf("error: %v\n", err)
			return
		}

		switch e := evt.(type) {
		case agent.MessageEvent:
			for _, part := range e.Response.Message.Content {
				if search, ok := part.(*llm.ToolSearchPart); ok && len(search.Tools) > 0 {
					fmt.Printf("  discovered: %s\n", strings.Join(search.Tools, ", "))
				}
			}
			u := e.Response.Usage
			fmt.Printf("  usage: input=%d cached=%d output=%d\n", u.InputTokens, u.CachedInputTokens, u.OutputTokens)

			if answer := e.Response.Message.TextContent(); answer != "" {
				fmt.Printf("\nassistant: %s\n", answer)
			}
		case agent.ToolRequestEvent:
			fmt.Printf("  -> %s %s\n", e.Request.Name, compact(e.Request.Arguments))
		case agent.ToolResponseEvent:
			fmt.Printf("  <- %s %s\n", e.Response.Name, compact(e.Response.Result))
		}
	}

	sess, err := store.Load(ctx, sessionID)
	if err != nil {
		fmt.Printf("error: load session: %v\n", err)
		return
	}

	fmt.Printf("\nloaded so far (session metadata): %v\n", sess.Metadata["ai-sdk-go/loaded_tools"])
}

// requestLogger prints the tools array of every model call. A load shows up
// as the array growing on the fallback path; native discovery keeps it stable.
type requestLogger struct{ calls int }

func (l *requestLogger) InterceptModel(_ context.Context, info *agent.ModelCallInfo, next agent.ModelCallHandler) agent.ModelCallHandler {
	l.calls++

	names := make([]string, 0, len(info.Req.Tools))
	for _, def := range info.Req.Tools {
		names = append(names, def.Name)
	}

	fmt.Printf("\nmodel call %d: native search=%t, %d tools [%s]\n", l.calls, info.Req.ToolSearch, len(names), strings.Join(names, " "))

	return next
}

func newModel() (llm.Model, error) {
	if key := os.Getenv("ANTHROPIC_API_KEY"); key != "" {
		provider, err := anthropic.NewProvider(key, anthropic.WithCaching())
		if err != nil {
			return nil, err
		}

		return provider.NewModel(anthropic.ModelClaudeSonnet46)
	}

	if key := os.Getenv("OPENAI_API_KEY"); key != "" {
		provider, err := openai.NewProvider(key)
		if err != nil {
			return nil, err
		}

		return provider.NewModel(openai.ModelGPT5_6)
	}

	return nil, fmt.Errorf("no ANTHROPIC_API_KEY or OPENAI_API_KEY set")
}

func compact(raw json.RawMessage) string {
	var buf bytes.Buffer
	if err := json.Compact(&buf, raw); err != nil {
		return string(raw)
	}

	s := buf.String()
	if len(s) > 160 {
		return s[:160] + "…"
	}

	return s
}

func indent(s string) string {
	return "  " + strings.ReplaceAll(s, "\n", "\n  ")
}
