// Copyright 2026 Redpanda Data, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package llm

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// Message represents a single message in a conversation.
// Messages form the conversation history and current context for the model.
type Message struct {
	// Role indicates who sent this message
	Role MessageRole `json:"role"`

	// Content carries the message content as a slice of Part values. Each
	// element is one of the concrete *llm.TextPart / *llm.ToolRequestPart /
	// *llm.ToolResponsePart / *llm.ReasoningPart pointer types.
	Content []Part `json:"content"`
}

// MessageRole defines who sent a message in the conversation.
type MessageRole string

const (
	// RoleUser indicates the message was sent by the end user.
	RoleUser MessageRole = "user"

	// RoleAssistant indicates the message was generated by the AI model.
	RoleAssistant MessageRole = "assistant"

	// RoleSystem indicates the message provides system-level context or instructions.
	// Only used if the model supports system prompts (check Capabilities.SystemPrompts).
	RoleSystem MessageRole = "system"
)

// NewMessage creates a message with the specified role and parts.
// This is the recommended way to construct messages for LLM requests.
//
// For simple text messages, pass a single text part:
//
//	msg := llm.NewMessage(llm.RoleUser, llm.NewTextPart("Hello"))
//
// For multi-part messages, pass multiple parts:
//
//	msg := llm.NewMessage(llm.RoleAssistant,
//	    llm.NewTextPart("I'll search for that."),
//	    llm.NewToolRequestPart(id, name, args),
//	)
func NewMessage(role MessageRole, parts ...Part) Message {
	return Message{
		Role:    role,
		Content: parts,
	}
}

// TextContent extracts and combines all text content from this message.
// Non-text parts are ignored.
func (m *Message) TextContent() string {
	return JoinTextParts(m.Content)
}

// ToolRequests extracts all tool request parts from this message.
// This is useful for agents that need to process tool calls from assistant messages.
func (m *Message) ToolRequests() []*ToolRequestPart {
	var out []*ToolRequestPart

	for _, part := range m.Content {
		if tr, ok := part.(*ToolRequestPart); ok && tr != nil {
			out = append(out, tr)
		}
	}

	return out
}

// HasToolRequests reports whether this message contains at least one tool
// request part. This is more efficient than `len(m.ToolRequests()) > 0`
// because it short-circuits on the first match.
func (m *Message) HasToolRequests() bool {
	for _, part := range m.Content {
		if _, ok := part.(*ToolRequestPart); ok {
			return true
		}
	}

	return false
}

// ToolResponses extracts all tool response parts from this message.
// This is useful when processing tool execution results.
func (m *Message) ToolResponses() []*ToolResponsePart {
	var out []*ToolResponsePart

	for _, part := range m.Content {
		if tr, ok := part.(*ToolResponsePart); ok && tr != nil {
			out = append(out, tr)
		}
	}

	return out
}

// MarshalJSON serializes Message with custom envelope-based Part encoding so
// the sealed-interface discriminated union survives JSON round-trips.
func (m Message) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString(`{"role":`)

	roleBytes, err := json.Marshal(m.Role)
	if err != nil {
		return nil, fmt.Errorf("llm: marshal Message role: %w", err)
	}

	buf.Write(roleBytes)
	buf.WriteString(`,"content":`)

	if m.Content == nil {
		buf.WriteString("null")
	} else {
		buf.WriteByte('[')

		for i, p := range m.Content {
			if i > 0 {
				buf.WriteByte(',')
			}

			pb, err := MarshalPart(p)
			if err != nil {
				return nil, fmt.Errorf("llm: marshal Message.Content[%d]: %w", i, err)
			}

			buf.Write(pb)
		}

		buf.WriteByte(']')
	}

	buf.WriteByte('}')

	return buf.Bytes(), nil
}

// UnmarshalJSON decodes a Message including the discriminated-union Content
// slice. Each element is dispatched through UnmarshalPart.
func (m *Message) UnmarshalJSON(data []byte) error {
	var wire struct {
		Role    MessageRole       `json:"role"`
		Content []json.RawMessage `json:"content"`
	}

	if err := json.Unmarshal(data, &wire); err != nil {
		return fmt.Errorf("llm: decode Message: %w", err)
	}

	m.Role = wire.Role

	if wire.Content == nil {
		m.Content = nil
		return nil
	}

	parts := make([]Part, 0, len(wire.Content))

	for i, raw := range wire.Content {
		p, err := UnmarshalPart(raw)
		if err != nil {
			return fmt.Errorf("llm: decode Message.Content[%d]: %w", i, err)
		}

		parts = append(parts, p)
	}

	m.Content = parts

	return nil
}
