// Copyright 2026 Redpanda Data, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package llm

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// Message represents a single message in a conversation.
// Messages form the conversation history and current context for the model.
type Message struct {
	// Role indicates who sent this message.
	Role MessageRole `json:"role"`

	// Content holds the message body using the sealed-interface Part
	// type. JSON encoding wraps each Part in a "{type: ...}" envelope.
	Content []Part `json:"-"`
}

// messageJSON is the wire format for Message. Content is serialised via
// the explicit Part envelope so the sealed-interface concrete types
// round-trip across JSON boundaries.
type messageJSON struct {
	Role    MessageRole       `json:"role"`
	Content []json.RawMessage `json:"content"`
}

// MessageRole defines who sent a message in the conversation.
type MessageRole string

const (
	// RoleUser indicates the message was sent by the end user.
	RoleUser MessageRole = "user"

	// RoleAssistant indicates the message was generated by the AI model.
	RoleAssistant MessageRole = "assistant"

	// RoleSystem indicates the message provides system-level context or instructions.
	// Only used if the model supports system prompts (check Capabilities.SystemPrompts).
	RoleSystem MessageRole = "system"
)

// NewMessage creates a message with the specified role and parts.
// This is the recommended way to construct messages for LLM requests.
//
// For simple text messages, pass a single text part:
//
//	msg := llm.NewMessage(llm.RoleUser, llm.NewTextPart("Hello"))
//
// For multi-part messages, pass multiple parts:
//
//	msg := llm.NewMessage(llm.RoleAssistant,
//	    llm.NewTextPart("I'll search for that."),
//	    llm.NewToolRequestPart("call_1", "search", args),
//	)
//
// For tool responses, use the user role:
//
//	msg := llm.NewMessage(llm.RoleUser,
//	    llm.NewToolResponsePart("call_1", "search", result),
//	)
func NewMessage(role MessageRole, parts ...Part) Message {
	return Message{
		Role:    role,
		Content: parts,
	}
}

// TextContent extracts and combines all text content from this message.
// Non-text parts are ignored.
func (m *Message) TextContent() string {
	return JoinTextParts(m.Content)
}

// ToolRequests extracts all tool request parts from this message.
// This is useful for agents that need to process tool calls from assistant messages.
func (m *Message) ToolRequests() []*ToolRequestPart {
	return PartsOfType[*ToolRequestPart](m.Content)
}

// ToolResponses extracts all tool response parts from this message.
// This is useful when processing tool execution results.
func (m *Message) ToolResponses() []*ToolResponsePart {
	return PartsOfType[*ToolResponsePart](m.Content)
}

// MarshalJSON implements json.Marshaler for Message.
func (m Message) MarshalJSON() ([]byte, error) {
	out := messageJSON{
		Role:    m.Role,
		Content: make([]json.RawMessage, len(m.Content)),
	}

	for i, p := range m.Content {
		data, err := MarshalPart(p)
		if err != nil {
			return nil, fmt.Errorf("encode message part %d: %w", i, err)
		}

		out.Content[i] = data
	}

	return json.Marshal(out)
}

// UnmarshalJSON implements json.Unmarshaler for Message.
func (m *Message) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		return nil
	}

	var in messageJSON
	if err := json.Unmarshal(data, &in); err != nil {
		return err
	}

	m.Role = in.Role
	m.Content = make([]Part, 0, len(in.Content))

	for i, raw := range in.Content {
		p, err := UnmarshalPart(raw)
		if err != nil {
			return fmt.Errorf("decode message part %d: %w", i, err)
		}

		m.Content = append(m.Content, p)
	}

	return nil
}
