package llm

// Message represents a single message in a conversation.
// Messages form the conversation history and current context for the model.
type Message struct {
	// Role indicates who sent this message
	Role MessageRole `json:"role"`

	// Content contains the message content using the extensible Part system.
	// This allows for rich content including text, images, tool calls, etc.
	Content []*Part `json:"content"`
}

// MessageRole defines who sent a message in the conversation.
type MessageRole string

const (
	// RoleUser indicates the message was sent by the end user.
	RoleUser MessageRole = "user"

	// RoleAssistant indicates the message was generated by the AI model.
	RoleAssistant MessageRole = "assistant"

	// RoleSystem indicates the message provides system-level context or instructions.
	// Only used if the model supports system prompts (check Capabilities.SystemPrompts).
	RoleSystem MessageRole = "system"

	// RoleTool indicates the message contains the result of a tool execution.
	// These messages are responses to tool requests from the assistant.
	RoleTool MessageRole = "tool"
)

// NewMessage creates a message with the specified role and parts.
// This is the recommended way to construct messages for LLM requests.
//
// For simple text messages, pass a single text part:
//
//	msg := llm.NewMessage(llm.RoleUser, llm.NewTextPart("Hello"))
//
// For multi-part messages, pass multiple parts:
//
//	msg := llm.NewMessage(llm.RoleAssistant,
//	    llm.NewTextPart("I'll search for that."),
//	    llm.NewToolRequestPart(toolReq),
//	)
//
// For tool responses, use the tool role:
//
//	msg := llm.NewMessage(llm.RoleTool, llm.NewToolResponsePart(resp))
func NewMessage(role MessageRole, parts ...*Part) Message {
	return Message{
		Role:    role,
		Content: parts,
	}
}

// TextContent extracts and combines all text content from this message.
// Non-text parts are ignored.
func (m *Message) TextContent() string {
	return JoinTextParts(m.Content)
}

// ToolRequests extracts all tool requests from this message.
// This is useful for agents that need to process tool calls from assistant messages.
func (m *Message) ToolRequests() []*ToolRequest {
	var toolRequests []*ToolRequest

	for _, part := range m.Content {
		if part.IsToolRequest() && part.ToolRequest != nil {
			toolRequests = append(toolRequests, part.ToolRequest)
		}
	}

	return toolRequests
}

// HasToolRequests returns true if this message contains any tool requests.
// This is more readable than checking len(msg.ToolRequests()) > 0.
func (m *Message) HasToolRequests() bool {
	for _, part := range m.Content {
		if part.IsToolRequest() {
			return true
		}
	}

	return false
}

// ToolResponses extracts all tool responses from this message.
// This is useful when processing tool execution results.
func (m *Message) ToolResponses() []*ToolResponse {
	var toolResponses []*ToolResponse

	for _, part := range m.Content {
		if part.IsToolResponse() && part.ToolResponse != nil {
			toolResponses = append(toolResponses, part.ToolResponse)
		}
	}

	return toolResponses
}

// FilterParts returns all parts of the specified kind.
// This provides a generic way to extract parts by type.
func (m *Message) FilterParts(kind PartKind) []*Part {
	var filtered []*Part

	for _, part := range m.Content {
		if part.Kind == kind {
			filtered = append(filtered, part)
		}
	}

	return filtered
}
