#!/usr/bin/env python3
"""Render the PR audit record (sticky comment, step summary, and the approving
review's body). Every evaluated PR gets one: verdict, config/prompt version,
model, guardrail and supply-chain results, and a link to the run. Best-effort
loads mean it renders even when an earlier step failed."""

from __future__ import annotations

import argparse

from common import load_json

MARKER = "<!-- ai-approved-merge -->"

MISSING_GUARDRAILS = {
    "eligible": False,
    "reasons": [
        "internal error: guardrails were not evaluated (an earlier pipeline "
        "step failed) — see the run link"
    ],
    "config_version": "unknown",
    "is_dependency": False,
}


def render(
    guardrails: dict,
    verdict: dict | None,
    decision: dict | None,
    run_url: str,
    dry_run: bool = False,
    approve_outcome: str = "",
) -> str:
    approve = bool((decision or {}).get("approve"))
    if dry_run:
        status = (
            "🟡 Would approve — dry run (no approval posted)"
            if approve
            else "⏸️ Human review required — dry run"
        )
    elif approve:
        # Reflect what actually happened, not just what was decided.
        if approve_outcome == "head-moved":
            status = ("⏸️ Approval decided but NOT posted — new commits arrived during "
                      "review; the new push is re-evaluated")
        elif approve_outcome in ("", "success"):
            status = "✅ AI-approved — merging is the author's call"
        else:
            status = (f"⚠️ Approval decided but the approve step did not succeed "
                      f"({approve_outcome}) — see run")
    else:
        status = "⏸️ Human review required"

    v = verdict or {}
    lines = [
        MARKER,
        f"### AI-approved merge — {status}",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Config version | `{guardrails.get('config_version', 'unknown')}` |",
        f"| Prompt version | `{v.get('prompt_version', 'n/a')}` |",
        f"| Model | `{v.get('model', 'n/a')}` |",
        f"| AI verdict | `{v.get('verdict', 'n/a')}` (confidence {v.get('confidence', 'n/a')}, "
        f"reviewed fully: {v.get('reviewed_fully', 'n/a')}, scope: {v.get('scope', 'n/a')}) |",
        f"| Files / lines (all) | {guardrails.get('changed_files', '?')} / "
        f"{guardrails.get('total_lines', '?')} |",
        f"| Reviewable files / lines | {guardrails.get('reviewable_files', '?')} / "
        f"{guardrails.get('reviewable_lines', '?')} |",
        f"| Generated (CI-verified) files / lines | {len(guardrails.get('generated_files') or [])} / "
        f"{guardrails.get('generated_lines', 0)} |",
        f"| Test / source lines | {guardrails.get('test_lines', '?')} / "
        f"{guardrails.get('source_lines', '?')} "
        f"(tests changed with source: {guardrails.get('tests_changed_with_source', '?')}) |",
        f"| Dependency update | {guardrails.get('is_dependency', False)} |",
        f"| Run | {run_url} |",
    ]

    if v.get("summary"):
        lines += ["", "**Review summary**", "", str(v["summary"])]
    concerns = v.get("concerns") if isinstance(v.get("concerns"), list) else []
    if concerns:
        lines += ["", "**Concerns**"] + [f"- {c}" for c in concerns]

    if guardrails.get("generated_files"):
        lines += ["", "**Generated files (not sent to the model)**"] + [
            f"- {g}" for g in guardrails["generated_files"]
        ]

    if guardrails.get("is_dependency"):
        sc = v.get("supply_chain")
        sc = sc if isinstance(sc, dict) else {}
        lines += [
            "",
            "**Supply-chain checks**",
            f"- checked: {sc.get('checked')}",
            f"- new maintainers: {sc.get('new_maintainers')}",
            f"- unusual version jump: {sc.get('unusual_version_jump')}",
            f"- added install scripts: {sc.get('added_install_scripts')}",
        ]
        if sc.get("notes"):
            lines += [f"- notes: {sc['notes']}"]

    if not guardrails.get("eligible"):
        lines += ["", "**Not eligible — reasons**"] + [
            f"- {r}" for r in guardrails.get("reasons", [])
        ]
    if decision and decision.get("reasons") and not approve:
        lines += ["", "**Not auto-approved — reasons**"] + [
            f"- {r}" for r in decision["reasons"]
        ]

    lines += [
        "",
        "_Generated by the AI-approved-merge mechanism. The bot only "
        "posts an approval; the author merges. This is an audit record; the branch ruleset is "
        "what enforces it._",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--guardrails", required=True)
    ap.add_argument("--verdict", default="")
    ap.add_argument("--decision", default="")
    ap.add_argument("--run-url", required=True)
    ap.add_argument("--dry-run", default="false")
    ap.add_argument("--approve-outcome", default="")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    guardrails = load_json(args.guardrails)
    if not isinstance(guardrails, dict):
        guardrails = MISSING_GUARDRAILS
    verdict = load_json(args.verdict)
    decision = load_json(args.decision)

    body = render(
        guardrails,
        verdict if isinstance(verdict, dict) else None,
        decision if isinstance(decision, dict) else None,
        args.run_url,
        dry_run=str(args.dry_run).lower() == "true",
        approve_outcome=args.approve_outcome,
    )
    with open(args.out, "w") as fh:
        fh.write(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
