// Copyright 2026 Redpanda Data, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/redpanda-data/ai-sdk-go/catalog/snapshot"
)

// TestCommittedSnapshotIsFresh fails when catalog/snapshot.json no longer
// matches the authored catalogs. Living in the unit-test suite means the
// ordinary test job enforces it — no workflow needs to remember a
// dedicated `task catalog:check` step. Regenerate with
// `task catalog:snapshot`.
func TestCommittedSnapshotIsFresh(t *testing.T) {
	t.Parallel()

	var generated bytes.Buffer
	require.NoError(t, snapshot.Encode(&generated, allCatalogs()...))

	path := filepath.Join("..", "..", "catalog", "snapshot.json")

	committed, err := os.ReadFile(path)
	require.NoError(t, err)

	if !bytes.Equal(committed, generated.Bytes()) {
		t.Fatalf("%s is stale: the authored catalogs no longer match the committed snapshot.\nRun `task catalog:snapshot` and commit the result.", path)
	}
}
